### ISSUE TITLE
All tests skipped when using --build-tag option

### ISSUE THREAD

**Issue by rcernich** [jboss-container-images/concreate#133]
Test runner should probably use the name specified in image.yaml to identify which tests should be activated instead of the tag used to create the image.  For example, running concreate with ``--build-tag=my-repo/rcernich/eap64-openshift:CLOUD-1234`` results in all tests being skipped.

**Comment by dbecvarik** [comment]
What version of concreate are you using? This should be fixed in 0.3.

**Comment by rcernich** [comment]
I was using 1.2.1.  I'll try with the new version.

**Comment by dbecvarik** [comment]
I think, this should be working in latest release, closing. Please reopen if it persists.
