### ISSUE TITLE
Revisit [repository] section in configuration file

### ISSUE THREAD

**Issue by goldmann** [jboss-container-images/concreate#26]
It is not a good idea to set `urls` for repositories globally, because there may be different requirements for different images.

**Comment by goldmann** [comment]
@dbecvarik @rcernich Any comments?

**Comment by jmtd** [comment]
I agree with you on this one, it could causes surprises if you are building images from a variety of different authors and urls set in your global configuration and perhaps forget about it.

**Comment by rcernich** [comment]
Typically, you'd have an option to specify the config.  I think it's fine to look for ``~/.concreate``, but being able to specify ``--config=release.concreate`` would help a lot (or maybe ``--globals``?).  That said, they are referenced in the Dockerfile, so maybe it makes sense to declare them in the yaml.  I don't know what that would look like, as I'm guessing this information is not transportable, other than the raw file name, e.g. ``jboss-rhel-os.repo``, leaving it to the user to provide the actual file.  Is it possible to define multiple repos in a single file?  What happens if the file is empty?  (I'm thinking we could add empty file(s) in the repo and mark them as untracked?)

Also, maybe instead of copying the repos into the image, we could mount a ``repos`` directory into the image and use that instead.  Just an idea.

**Comment by goldmann** [comment]
Thanks Rob for your ideas. These are always valuable!

Let me try to reply one by one.

>  Is it possible to define multiple repos in a single file?
Generally speaking - yes. There is no limit in number of repositories added in a single repo file. The only requirement is that the id (between square bracket) is unique.

This is not true for the current implementation in Concreate. We require that every repo is stored in separate file, the repo id is the same as the file name. This way we have control over what we add, what we enable and what we remove after building the image. This section tried to explain requirements: http://concreate.readthedocs.io/en/develop/configuration.html#repository

> What happens if the file is empty?

YUM/DNF wise - nothing, but current implementation of Concreate will try to enable repo with name defined as the repo file name. This will obviously fails since repo that id will not be found. This failure is fatal.

> Also, maybe instead of copying the repos into the image, we could mount a repos directory into the image and use that instead.

Not supported in container build system we use.

----

My concern is that, although defining them in `.concreate` may be convenient, it can be misleading in cases like:

- One image requires just a subset of "globally" defined repositories
- One image cannot use a specific "global" repository, because it has conflicts with other repository (unlikely, but can happen)
- We build images based on different operating systems (RHEL vs. CentOS vs. Fedora).

Considering above, IMHO we need to define requirements like this:

1. Additional repositories must be **defined per image**, not globally.
2. Additional repository files could be **committed directly to repository** (example could be a public repo for community image) or **referenced locally or via URL** (internal repository use case)
3. **It should be easy to define repositories**.
    This cannot be done (only) via CLI, because ideally we would set it once. In case of CLI - we would need to remember to set it on every invocation, which is less than optimal.
4. After some investigation, considering container best practices, I think we **should always remove added repositories at the end of the build process**, so this part of implementation should not change.

**Comment by goldmann** [comment]
How about this:

1. Adjust slightly the `[repository]` section in the configuration file (possibly rename it to `[repositories]`) in following way:
    * Remove `url` key
    * Allow to define arbitrary keys in this section: `jboss-rhel-os = http://url.to/jboss-rhel-os.repo`
    * More than one URL could be defined for a particular key.
    * URL's and local path to files should be supported
2. In image definition add a `repositories` section (or even merge it with `packages` section) where we could define which repo name should be used.

Of course keys in configuration file would could be defined by the user. We could use even image names or other ID's to "group" repos.

**Example:**

Concreate configuration file:

```
[repositories]
jboss-ocp=http://host/jboss-rhel-os.repo,http://host/jboss-rhel-ocp.repo,http://host/jboss-rhel-rhscl.repo
other-repos=http://otherhost.com/osme.repo
```

Image descriptor:

```yaml
packages:
  repositories:
    - jboss-ocp
  install:
    - openssl
    - java
```

This way we have full control over what is used by an image and we still have flexibility of defining it in a free way.

Another improvement (to current implementation) would be to use `yum-config-manager --add-repo=REPO_FILE` to actually install and enable requested repo files instead of doing it manually.

@dbecvarik @jmtd @rcernich Comments?

**Comment by rcernich** [comment]
I've exhausted my expertise with respect to yum, etc.  My only comment would be how this affects the build metadata, i.e. whether it's part of external configuration (.concreate) or part of the image.yaml.  In the ``packages`` example above, what would be expected of the user?  I assume they'd need a jboss-ocp.repo file defined somewhere, but what should its contents be?  What if they want to use a standard repo (I'm assuming we might want to specify a specific repo for certain artifacts, e.g. to pick up newer builds; individual projects might want this too, for CI, other might not care where the packages come from)?

Like I said, this is a bit beyond my expertise at this point.

**Comment by goldmann** [comment]
I guess your comments are more about handling repo files. Let me try to clarify.

> In the packages example above, what would be expected of the user?

Use should define the `jboss-ocp` property in `~/.concreate`, for example in the way as proposed in the example. These repo files (regular YUM/DNF repo files) obviously need to be prepared by the user (or someone else).

Regarding content of the repo file, this may help: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/sec-Configuring_Yum_and_Yum_Repositories.html#sec-Setting_repository_Options

> What if they want to use a standard repo?

There will be no interference. Standard repos will be available as part of the YUM process. Yes, this is different from what we have now - where we disable all repos and enable only added repos. I've tried it locally and it should build fine on our build system.

**Comment by rcernich** [comment]
Sounds good to me.  Thanks for the explanation.

**Comment by goldmann** [comment]
Closed via https://github.com/jboss-container-images/concreate/pull/45.
