### ISSUE TITLE
Refactor schema definitions to reuse common elements

### ISSUE THREAD

**Issue by rcernich** [jboss-container-images/concreate#32]
There is not much difference between the three existing schema (image, overrides, module).  It would be nice to define common elements in one place and include them in the specific schema.  This would ease the maintenance burden and would allow the code related to the fields to be common across them (well, this is the way it is, but it prevents missing a schema update should the implementation change).

**Comment by goldmann** [comment]
Yes, this is planned. We see this too.

**Comment by goldmann** [comment]
I was looking at this today as part of module definitions reorganizing and was hit by this issue: https://github.com/Grokzen/pykwalify/issues/88. This is a blocker for us to use pykwalify `1.6.0` and still trying to use common elements across our validations. It seems that fix for this is hanging there for a while... https://github.com/Grokzen/pykwalify/pull/100 and https://github.com/Grokzen/pykwalify/pull/108.

Possible solution is to downgrade to pykwalify `1.5.2`, but with this we loose the `assert` function.

**Comment by dbecvarik** [comment]
cannot we just simply have "common schema" included once in image, module, overrides for now and refactor to better inclusion in more granular way later?

**Comment by goldmann** [comment]
I'm not sure what you mean. Schemas for override and for image are different.

**Comment by goldmann** [comment]
Either case - I'll have a proposal for this soonish.

**Comment by dbecvarik** [comment]
they are almost same as you can see:
https://www.diffchecker.com/5dJCARMK
and even some non required parts of overrides should be required (names for envs)...

**Comment by goldmann** [comment]
So, yes, a proposal is available in #42. I've tried several different approaches and found that this is the best one. There is one thing to note - I changed the behavior of `merge_dictionaries` method, where simple types are used from the second, not first dictionary. This seemed to me weird that we left them and caused issues with properly merging dictionaries for schemas.

**Comment by dbecvarik** [comment]
#42 seems to complicated for me. I don't like such a complex changes and us doing merge dictionaries for schema to fix library bug.

**Comment by goldmann** [comment]
Explain in details what is complicated there, please. It's a lot of refactoring, but look at the code instead.

**Comment by goldmann** [comment]
And no, I don't use that broken feature of pykwalify anymore in my PR.

**Comment by dbecvarik** [comment]
Also I'm strictly against changing/overriding schemas in runtime - schemas are now totally unclear to read by user. 
Schema should server not only concreate, but also can be used in editors to check if image.yaml is correct during development - need to run the tool to check the schema is weird behavior.
For example if I look at https://github.com/goldmann/concreate/blob/f12a629f63e9a03d7d60a9b2dcf11a8f8d29df09/concreate/schema/image.yaml  it seems only from is valid the image.yaml.

**Comment by goldmann** [comment]
You have everything in this file: https://github.com/goldmann/concreate/blob/f12a629f63e9a03d7d60a9b2dcf11a8f8d29df09/concreate/schema/schema.yaml. If there are **any** modifications needed on top of this common schema, you can find them in specific YAML files, like the one you mentioned above. It means - use everything from common, but for the `from` key - use this definition.

**Comment by dbecvarik** [comment]
Ok tell me how can I view complete schema for image, module and overrides? I can't now and i need to know how they're are merged/overrided which is not a part of a kwalify but our added logic which I think is not a good idea.

**Comment by goldmann** [comment]
You can't. This is the whole point of *reusing* and *sharing* image schema across multiple types of definitions (image, module, overrides). Common schema is defined somewhere and **only** specific changes are maintained separately, not the whole thing.

**Comment by goldmann** [comment]
> I can't now and i need to know how they're are merged/overrided which is not a part of a kwalify but our added logic which I think is not a good idea.

I can use this argument against image descriptor overrides: I cannot see the effective image descriptor when looking at a particular image descriptor file because everything is merged (sic!) at runtime...

But hey, this is a feature, right?

**Comment by dbecvarik** [comment]
yes but I think we are here to much after sharing and reusing. Why we cant have simple stuff like:
overrides schema
``` yaml
from: ...
name: ...
include labels
include envs
include ...
```
image schema
``` yaml
from: ...
include lables
include envs
```

**Comment by dbecvarik** [comment]
> I can use this argument against image descriptor overrides: I cannot see the effective image descriptor when looking at a particular image descriptor file because everything is merged (sic!) at runtime...

> But hey, this is a feature, right?
Effective image descriptor will be logged to target dir - IT was discussed before. 
I'm ok with merging schema, if you will just commit to repo after merging - so I can see them whole and have a simple tool to regenerate them from shared sources.

**Comment by goldmann** [comment]
> Why we cant have simple stuff like
Because this is unsupported in pykwalify.

**Comment by goldmann** [comment]
> I'm ok with merging schema, if you will just commit to repo after merging - so I can see them whole and have a simple tool to regenerate them from shared sources.

I don't get that request. What is the benefit of seeing the final schema? Schemas are for us - Concreate developers, to define what we expect from users. We know the schema. Documentation, together with error messages from schema validation is for users. If we (as developers) will debug issues in schemas - we should add debug statements to see the target schema, as usual.

**Comment by dbecvarik** [comment]
Oh ok, it seems that I misinterpreted kwalify manual. Hmm so probably your solution is the only possible one for now.

**Comment by goldmann** [comment]
I didn't find anything better while working on it for the last 6 hours...

**Comment by dbecvarik** [comment]
Ok. I made review of the PR. Its only minor adjustments- so decide if we need them.
