### ISSUE TITLE
Artifacts section comments

### ISSUE THREAD

**Issue by goldmann** [jboss-container-images/concreate#40]
I have a few comments about the `artifacts` section.

1. `file` should generally speaking not be available in the main image descriptor. The reason is that `file` is environment specific, whereas the image descriptor cannot be. It's fine to have `file` in the overrides schema where it makes sense to be defined.
2. I would rename `file` to `path`.
3. How we should define artifacts that are private and we want to only define the name of the artifact? I've received some critic about using the `url` scheme for this use case because a file name is not a URL. Thus we introduced `artifact`.
4. HInts for artifacts were removed. Why?

@rcernich @jmtd @dbecvarik

**Comment by rcernich** [comment]
> I have a few comments about the artifacts section.
>
>  1.  file should generally speaking not be available in the main image descriptor. The reason is that file is environment specific, whereas the image descriptor cannot be. It's fine to have file in the overrides schema where it makes sense to be defined.

I think this is irrelevant as it's part of the generic way of specifying resources.  Generally, these would be specified as download URLs in the image or module, but it's also possible that somebody just checked a jar into scm (yuck!).  Anyway, I don't think it hurts anything.  It also allows you to stub something out without error, e.g. if an artifact is not available for download, ``path: some-artifact.jar``

>  2.  I would rename file to path.

Agreed.

>  3.  How we should define artifacts that are private and we want to only define the name of the artifact? I've received some critic about using the url scheme for this use case because a file name is not a URL. Thus we introduced artifact.

See comment to item two: ``path: artifact-you-need-to-get-yourself.zip``

>  4.  HInts for artifacts were removed. Why?

As the new "resource" code applies to artifacts and repositories, ``description`` seemed a better fit than ``hint``.  Feel free to change it back if you prefer hint.

**Comment by goldmann** [comment]
I'll rename it to `path` and keep `description`.

**Comment by rcernich** [comment]
Just wanted to add one thing with respect to path resolution.  Relative paths should be resolved relative to the directory containing the module/image/overrides.yaml.  It works for image.yaml, but I need to verify that it works that way for the other metadata suppliers.

**Comment by rcernich** [comment]
....and it does.

**Comment by goldmann** [comment]
There is one issue with the usage of `path` for internally available artifacts. We should still be able to fetch them from cacher, but `PathResource`/`FileResource` works only for local artifacts. Thinking now how to solve it.
