### ISSUE TITLE
Add support for tests

### ISSUE THREAD

**Issue by rcernich** [jboss-container-images/concreate#43]
The test command should clean, generate, build and test the resulting image.

**Comment by dbecvarik** [comment]
i think it doesn't have to clean, build and generate - imagine scenario when you are developing test for the image, than you should be able to run some test only. 
We have proposal to our cli to be more like Makefile than maven. So we should be consistent with test target too.

**Comment by goldmann** [comment]
Done via: https://github.com/jboss-container-images/concreate/pull/85

**Comment by dbecvarik** [comment]
Test invocation was change. 
Concreate now doesn't support any kind of clean command (there is no need to implement rm -rf target for now in python)

The other difference that concreate doesnt run build for test execution - we need to support use cases when we want to run test for different existing image.

Only implicit operation for test subcommand is  generate which is used to fetch test features/steps from modules.
