### ISSUE TITLE
Set up COPR build for easier installation

### ISSUE THREAD

**Issue by goldmann** [jboss-container-images/concreate#44]
We should make it possible to consume Concreate via RPM from a YUM/DNF repo. This will simplify installation a lot.

https://copr.fedorainfracloud.org/

- [x] Prepare a spec file
- [x] Prepare COPR project
- [x] Execute first build
- [x] Update documentation

**Comment by goldmann** [comment]
https://copr.fedorainfracloud.org/coprs/goldmann/concreate/

**Comment by dbecvarik** [comment]
please do fedora-25 build too a lot of people are usually one version behind

**Comment by goldmann** [comment]
Yah, this is just a placeholder :)

**Comment by goldmann** [comment]
First issue: Fedora provides pykwalify 1.5.1, we require 1.6.0.
