### ISSUE TITLE
Add support for discovering modules stored next to image descriptor

### ISSUE THREAD

**Issue by goldmann** [jboss-container-images/concreate#46]

**Comment by dbecvarik** [comment]
its already supported. if the modules are in modules this next to image.yaml they.re take or not?

**Comment by dbecvarik** [comment]
this already worked https://github.com/dbecvarik/jboss-amq-6-openshift-image/tree/dogen3/modules with rc1. What this issue is about?

**Comment by goldmann** [comment]
After refactoring it stopped to work, probably regression: https://github.com/jboss-container-images/concreate/pull/18.

**Comment by dbecvarik** [comment]
Oh I see. We should create integration test very soon to have some repo with "working" image too.

**Comment by rcernich** [comment]
I removed that, as I thought it was better to explicitly define module repositories.  That was part of my change.
