### ISSUE TITLE
Should try original url/path when downloading resource from cache fails

### ISSUE THREAD

**Issue by rcernich** [jboss-container-images/concreate#77]
If an artifact is missing from the cache, the build will fail without trying to download the resource from the specified url/path.  This may be a misunderstanding regarding how the cache is meant to be used.  The understanding being the cache is used for performance, as opposed to restricting downloads to known, pre-verified artifacts.

**Comment by dbecvarik** [comment]
We spoke about this with Marek. We decided to try to download from url, if cache miss occurs.
