### ISSUE TITLE
Create a book of best practices

### ISSUE THREAD

**Issue by dbecvarik** [jboss-container-images/concreate#97]
We should provide a place where we can create/document short best practices snippets for concreate. This should be ideally in some wiki format where people can contribute easily.

**Comment by dbecvarik** [comment]
I'll probably start using wiki on github - its probably good enough

**Comment by dbecvarik** [comment]
Because we wanted this to be live and updated by community. It should be place where to share stuff. Or if we can enable part of read the docs to be updated with every commit it could serve too,

**Comment by goldmann** [comment]
It is always updated after every commit: http://concreate.readthedocs.io/en/develop/ (develop vs. latest) Additionally GH gives a nice preview for these files and we can use PR's from community. I see it just as a win.

**Comment by dbecvarik** [comment]
Closing, as decided, that this should be part of official docs.
